### ISSUE TITLE
Issue at NPM start

### ISSUE THREAD

**Issue by TGrandjeanLIST** [anders94/blockchain-demo#104]
Very very very good demo for newbies !!!!!

Having the following issue at startup ....  Any ideas ?

Thanks !!

/home/*******/blockchain-demo/node_modules/fast-printf/dist/src/tokenize.js:4
const TokenRule = /(?:%(?<flag>([+0-]|-\+))?(?<width>\d+)?(?<position>\d+\$)?(?<precision>\.\d+)?(?<conversion>[%BCESb-iosux]))|(\\%)/g;
                  ^

SyntaxError: Invalid regular expression: /(?:%(?<flag>([+0-]|-\+))?(?<width>\d+)?(?<position>\d+\$)?(?<precision>\.\d+)?(?<conversion>[%BCESb-iosux]))|(\\%)/: Invalid group
    at Object.<anonymous> (/home/******/blockchain-demo/node_modules/fast-printf/dist/src/tokenize.js:4:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/*****/blockchain-demo/node_modules/fast-printf/dist/src/createPrintf.js:5:20)
    at Module._compile (module.js:653:30)

**Comment by TGrandjeanLIST** [comment]
Ok Docker version is working fine.
